[tool.black]
line-length = 120
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120
default_section = "THIRDPARTY"
known_third_party = []
known_first_party = []

[tool.mypy]
exclude = [
    'venv',
    '\.venv',
    '\.git',
    '__pycache__',
    'main.py',
    'src',
]

[[tool.mypy.overrides]]
module = [
    "src.*",
]
ignore_missing_imports = true
